import { defineConfig, globalIgnores } from 'eslint/config'
import nextVitals from 'eslint-config-next/core-web-vitals'
import nextTs from 'eslint-config-next/typescript'

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Flat config does not read .gitignore, so generated and vendored output has
  // to be listed here explicitly or it gets linted.
  globalIgnores([
    // eslint-config-next defaults, restated because listing any ignores replaces them.
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',

    // Generated by `supabase start` — vendored edge-runtime source, not ours.
    'supabase/.temp/**',
    'supabase/.branches/**',

    // Generated SQL and snapshots.
    'drizzle/**',

    'coverage/**',
    'test-results/**',
    'playwright-report/**',
  ]),

  {
    // Playwright fixtures take a callback parameter named `use`, which the
    // React plugin mistakes for the `use()` hook. There is no React here.
    files: ['e2e/**/*.ts', 'playwright.config.ts'],
    rules: {
      'react-hooks/rules-of-hooks': 'off',
    },
  },
])

export default eslintConfig
